### PR TITLE
bump(charts): v1.0.0-alpha.8

### PR DESCRIPTION
**Pull request by golobitch**

### CODE REVIEW

**Comment by sabineschaller** [comment]
Why does the action complain about 
``` 
npm ERR! Missing script: "knex -- migrate:latest --env production"
```
Is that something in another PR that needs to go in first for this to not fail?

**Comment by sabineschaller** [comment]
Now we get 
```
failed installing charts: failed processing charts
Error: Process completed with exit code 1.
```

**Comment by golobitch** [comment]
> Now we get
> 
> ```
> failed installing charts: failed processing charts
> Error: Process completed with exit code 1.
> ```

This is general error, however, we can see few different errors here https://github.com/interledger/helm-charts/actions/runs/8636782800/job/23677473710

For example, look at line #151

```
getaddrinfo ENOTFOUND postgres.example.com
Error: getaddrinfo ENOTFOUND postgres.example.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
```

This is in init containers. It tries to run migrations manually in init containers, however, values are just an example values added. And also, it doesn't have any postgresql installed on this system. This is the same for `rafiki-auth` and `rafiki-backend`. It was tested locally with minikube and it works.

Furthermore, if we check line #430 we can see that frontend is failing due to that already known remix issue :)

This remix issue is easy solvable, but that with postgresql is not :)

**Comment by golobitch** [comment]
Moved to #35

**Pull request closed without merging**
